# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.qrph.qmod
canonical: https://profiles.ihe.net/QRPH/QMOD
version: 0.0.1-current
name: IHE_QRPH_QMOD
title: "Quality Measures for Occupational Data For Health"
description: This IHE profile will constrain quality reporting and measurement standards in the context of ODH to improve the ability to assess work-related risks and provide support for strategies to monitor and measure health impacts related to workplace conditions with specific content to support quality improvement efforts.
releaseLabel: ci-build
#releaseLabel: ballot
#releaseLabel: trial-use
#releaseLabel: release
#date: 2022-01-02
status: draft
publisher:
  ## Find your domain contact on the https://www.ihe.net/ihe_domains page
  - name: IHE Quality, Research and Public Health Committee
  - url: https://www.ihe.net/ihe_domains/quality_research_and_public_health/
  - email: iti@ihe.net
contact:
  - name: IHE Quality, Research and Public Health Committee
    telecom:
      - system: email
        value: qrph@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate. The order they appear here is the order they will appear in the TOC and on the next/prev navigation.
  index.md:
    title: ToDo Home
    generation: markdown
  volume-1.md:
    title: 1:XX ToDo Volume 1
    generation: markdown
  QRPH-60.md:
    title: 2:3.60 Query for ODH Quality Data [QRPH-60]
    generation: markdown
  domain-ZZ.md:
    title: 3:?.ZZ Content one [Domain-ZZ]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: "Download and Analysis"
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Actor Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 2:
    "Transaction one [QRPH-60]": QRPH-60.html
  Volume 3:
    "Content one [Domain-ZZ]": domain-ZZ.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html
